// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/project/sandbox/app.config";
import type { default as appConfig1 } from "/project/sandbox/node_modules/.pnpm/@shuriken-ui+nuxt@0.2.9/node_modules/@shuriken-ui/nuxt/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}